matrix:
  include:
    - language: node_js
      node_js:
        - '10'
      script:
        - ./scripts/ci-build-node.sh
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - tools
          - platform-tools
          - build-tools-25.0.3
          - build-tools-25.0.0
          - build-tools-23.0.1
          - build-tools-25.0.2
          - build-tools-26.0.1
          - build-tools-25.0.1
          - build-tools-28.0.3
          - android-25
          - android-23
          - android-26
          - android-28
      before_install:
        - nvm install 10
        - node --version
        - npm i -g npm@5.0.3
        - npm --version
      script:
        - travis_retry ./scripts/ci-build-android.sh
