language: node_js
node_js:
- "6"
matrix:
  include:
  - language: node_js
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
    install:
    - npm install
    script:
    - ./scripts/ci-build-node.sh
  - language: android
    jdk: oraclejdk8
    android:
      components:
        - tools
        - tools # tools twice because of bug: https://github.com/travis-ci/travis-ci/issues/6040
        - platform-tools # must come after the double tools to get the right version

        - build-tools-25.0.3
        - build-tools-23.0.1 # used by react-native-fetch-blob
        - build-tools-25.0.2 # used by react-native-video
        - build-tools-26.0.1 # used by react-native-vector-icons
        - android-25
        - android-23 # used by react-native-fetch-blob
        - android-26 # used by react-native-vector-icons
      licenses:
        - android-sdk-license-.+
    env:
    - CXX=g++-4.8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
    before_install:
    - nvm install 8
    - node --version
    - npm i -g npm@5.0.3
    - npm --version
    - npm install
    script:
    - travis_retry ./scripts/ci-build-android.sh
